import { ACCENT, BLUE, ACCENT_SOFT } from './data';

export const CLIENTS = [
  {
    id: 'dana',
    username: 'dana',
    password: 'portal123',
    contact: {
      initials: 'DW',
      name: 'Dana Whitfield',
      role: 'Brand Strategy Client',
      since: 'Client since March 2023',
      phone: '(415) 555-0148',
      email: 'dana@solsticeretail.com',
      address: '220 Market St, Suite 400, San Francisco, CA',
      company: 'Solstice Retail Co.',
      plan: 'Growth Retainer',
      notes: 'Prefers async updates over calls; monthly check-in scheduled for the 3rd of each month.',
    },
    leads: [
      { id: 1, name: 'Alex Rivera', company: 'Northbridge Realty', phone: '(628) 555-0110', email: 'alex@northbridgerealty.com', source: 'Website Form', status: 'New', value: 4200, dateAdded: 'Jul 16', notes: 'Requested info on the Q3 listing campaign package.' },
      { id: 2, name: 'Jamie Chen', company: 'Chen & Co. Law', phone: '(415) 555-0193', email: 'jamie@chenlaw.com', source: 'Referral', status: 'Contacted', value: 8500, dateAdded: 'Jul 12', notes: 'Follow up scheduled after the initial discovery call.' },
      { id: 3, name: 'Morgan Ellis', company: 'Ellis Home Goods', phone: '(510) 555-0166', email: 'morgan@ellishomegoods.com', source: 'Paid Ads', status: 'Qualified', value: 12000, dateAdded: 'Jul 9', notes: 'Budget confirmed; drafting proposal for a full-funnel campaign.' },
      { id: 4, name: 'Taylor Brooks', company: 'Brooks Fitness Studio', phone: '(925) 555-0142', email: 'taylor@brooksfitness.com', source: 'Referral', status: 'Proposal Sent', value: 6750, dateAdded: 'Jul 5', notes: 'Proposal sent Jul 5; awaiting sign-off from ownership.' },
      { id: 5, name: 'Sam Okafor', company: 'Okafor Dental Group', phone: '(650) 555-0177', email: 'sam@okafordental.com', source: 'Cold Outreach', status: 'Won', value: 15300, dateAdded: 'Jun 28', notes: 'Signed for the annual retainer starting August.' },
      { id: 6, name: 'Riley Foster', company: 'Foster Landscaping', phone: '(408) 555-0129', email: 'riley@fosterlandscaping.com', source: 'Website Form', status: 'Lost', value: 3100, dateAdded: 'Jun 20', notes: 'Went with an in-house solution.' },
    ],
    appointments: [
      { id: 1, title: 'Q3 Brand Strategy Call', date: '2026-07-14', time: '10:00 AM', duration: '45 min', location: 'Zoom', type: 'Strategy Call', status: 'completed', notes: 'Reviewed Q3 campaign direction and budget allocation across channels.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }, { name: 'Dana Whitfield', initials: 'DW', color: ACCENT }] },
      { id: 2, title: 'Creative Concept Review', date: '2026-07-22', time: '2:00 PM', duration: '60 min', location: 'Agency HQ — Conf Room B', type: 'Creative Review', status: 'confirmed', notes: 'Bring feedback on the three logo directions before the session.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }, { name: 'Marcus Lee', initials: 'ML', color: ACCENT }] },
      { id: 3, title: 'Quarterly Business Review', date: '2026-07-24', time: '11:00 AM', duration: '90 min', location: 'Zoom', type: 'QBR', status: 'confirmed', notes: 'Full performance recap and Q4 planning discussion.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }] },
      { id: 4, title: 'Paid Media Kickoff', date: '2026-07-29', time: '9:30 AM', duration: '30 min', location: 'Phone', type: 'Kickoff', status: 'pending', notes: 'Confirm ad spend and channel mix for August before kicking off.', attendees: [{ name: 'Marcus Lee', initials: 'ML', color: ACCENT }] },
      { id: 5, title: 'Monthly Check-In', date: '2026-08-03', time: '10:00 AM', duration: '30 min', location: 'Zoom', type: 'Check-In', status: 'confirmed', notes: 'Standing monthly sync on retainer progress.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }] },
    ],
    notifications: [
      { id: 1, title: 'Upcoming appointment', body: 'Creative Concept Review starts in 2 days', time: 'Today, 9:00 AM', unread: true, glyph: '🕑', iconBg: ACCENT_SOFT },
      { id: 2, title: 'Appointment confirmed', body: 'Quarterly Business Review confirmed for Jul 24', time: 'Yesterday', unread: true, glyph: '✓', iconBg: 'rgba(15,23,42,0.06)' },
      { id: 3, title: 'Message from Priya Shah', body: 'Sent over the updated brand deck ahead of Friday', time: 'Jul 18', unread: false, glyph: '✉', iconBg: ACCENT_SOFT },
      { id: 4, title: 'Invoice ready', body: 'Your monthly invoice is ready to view', time: 'Jul 15', unread: false, glyph: '$', iconBg: 'rgba(15,23,42,0.06)' },
      { id: 5, title: 'Appointment rescheduled', body: 'Paid Media Kickoff was moved to Jul 29', time: 'Jul 12', unread: false, glyph: '↻', iconBg: ACCENT_SOFT },
    ],
  },
  {
    id: 'jordan',
    username: 'jordan',
    password: 'portal123',
    contact: {
      initials: 'JR',
      name: 'Jordan Reyes',
      role: 'Growth Marketing Client',
      since: 'Client since January 2025',
      phone: '(312) 555-0122',
      email: 'jordan@reyesvancedental.com',
      address: '88 LaSalle St, Suite 1200, Chicago, IL',
      company: 'Reyes & Vance Dental Group',
      plan: 'Launch Retainer',
      notes: 'Prefers Tuesday afternoons for calls; wants weekly ad-spend recaps by email.',
    },
    leads: [
      { id: 1, name: 'Elena Vargas', company: 'Vargas Orthodontics', phone: '(773) 555-0166', email: 'elena@vargasortho.com', source: 'Referral', status: 'New', value: 5400, dateAdded: 'Jul 17', notes: 'Interested in a second-location launch package.' },
      { id: 2, name: 'Ben Coleman', company: 'Coleman Family Dental', phone: '(312) 555-0184', email: 'ben@colemandental.com', source: 'Paid Ads', status: 'Contacted', value: 7200, dateAdded: 'Jul 14', notes: 'Discovery call booked for next week.' },
      { id: 3, name: 'Priya Nair', company: 'Nair Pediatric Care', phone: '(630) 555-0141', email: 'priya@nairpediatric.com', source: 'Website Form', status: 'Qualified', value: 9800, dateAdded: 'Jul 10', notes: 'Reviewing proposal for a full rebrand + local SEO package.' },
      { id: 4, name: 'Grace Kim', company: 'Kim Wellness Dental', phone: '(847) 555-0113', email: 'grace@kimwellnessdental.com', source: 'Cold Outreach', status: 'Won', value: 11400, dateAdded: 'Jun 30', notes: 'Signed on for the annual growth retainer.' },
      { id: 5, name: 'Owen Marsh', company: 'Marsh Dental Studio', phone: '(773) 555-0197', email: 'owen@marshdental.com', source: 'Referral', status: 'Lost', value: 4600, dateAdded: 'Jun 22', notes: 'Went with a competing agency.' },
    ],
    appointments: [
      { id: 1, title: 'Q3 Growth Strategy Call', date: '2026-07-15', time: '1:00 PM', duration: '45 min', location: 'Zoom', type: 'Strategy Call', status: 'completed', notes: 'Aligned on Q3 ad spend and new patient acquisition targets.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }, { name: 'Jordan Reyes', initials: 'JR', color: ACCENT }] },
      { id: 2, title: 'Landing Page Creative Review', date: '2026-07-21', time: '11:00 AM', duration: '45 min', location: 'Zoom', type: 'Creative Review', status: 'confirmed', notes: 'Review the two new landing page concepts before launch.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }] },
      { id: 3, title: 'Quarterly Business Review', date: '2026-07-27', time: '2:00 PM', duration: '90 min', location: 'Phone', type: 'QBR', status: 'confirmed', notes: 'Full Q3 performance recap and Q4 planning.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }] },
      { id: 4, title: 'Monthly Check-In', date: '2026-08-04', time: '1:00 PM', duration: '30 min', location: 'Zoom', type: 'Check-In', status: 'confirmed', notes: 'Standing monthly sync on retainer progress.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }] },
    ],
    notifications: [
      { id: 1, title: 'Upcoming appointment', body: 'Landing Page Creative Review starts tomorrow', time: 'Today, 8:00 AM', unread: true, glyph: '🕑', iconBg: ACCENT_SOFT },
      { id: 2, title: 'New lead assigned', body: 'Grace Kim marked as Won — nice work!', time: 'Jun 30', unread: false, glyph: '✓', iconBg: 'rgba(15,23,42,0.06)' },
      { id: 3, title: 'Message from Priya Shah', body: 'Shared the updated landing page concepts', time: 'Jul 17', unread: false, glyph: '✉', iconBg: ACCENT_SOFT },
      { id: 4, title: 'Invoice ready', body: 'Your monthly invoice is ready to view', time: 'Jul 15', unread: false, glyph: '$', iconBg: 'rgba(15,23,42,0.06)' },
    ],
  },
  {
    id: 'casey',
    username: 'casey',
    password: 'portal123',
    contact: {
      initials: 'CN',
      name: 'Casey Nakamura',
      role: 'Brand & Social Client',
      since: 'Client since September 2024',
      phone: '(206) 555-0136',
      email: 'casey@nakamurawellness.com',
      address: '410 Pike St, Seattle, WA',
      company: 'Nakamura Wellness Studio',
      plan: 'Essentials Plan',
      notes: 'Prefers Slack for quick updates; monthly review call on the first Monday.',
    },
    leads: [
      { id: 1, name: 'Maya Torres', company: 'Torres Yoga Collective', phone: '(206) 555-0155', email: 'maya@torresyoga.com', source: 'Instagram', status: 'New', value: 2800, dateAdded: 'Jul 18', notes: 'Asked about a social content + community package.' },
      { id: 2, name: 'Liam Foster', company: 'Foster Pilates Studio', phone: '(425) 555-0177', email: 'liam@fosterpilates.com', source: 'Referral', status: 'Contacted', value: 3600, dateAdded: 'Jul 13', notes: 'Intro call scheduled for later this week.' },
      { id: 3, name: 'Aisha Bello', company: 'Bello Barre Studio', phone: '(206) 555-0198', email: 'aisha@bellobarre.com', source: 'Website Form', status: 'Won', value: 4900, dateAdded: 'Jun 27', notes: 'Signed on for the Essentials Plan starting August.' },
      { id: 4, name: 'Noah Kim', company: 'Kim Cycle House', phone: '(360) 555-0142', email: 'noah@kimcyclehouse.com', source: 'Paid Ads', status: 'Lost', value: 3100, dateAdded: 'Jun 19', notes: 'Paused marketing spend for the season.' },
    ],
    appointments: [
      { id: 1, title: 'Brand Refresh Kickoff', date: '2026-07-16', time: '10:30 AM', duration: '45 min', location: 'Zoom', type: 'Kickoff', status: 'completed', notes: 'Kicked off the summer brand refresh and content calendar.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }, { name: 'Casey Nakamura', initials: 'CN', color: ACCENT }] },
      { id: 2, title: 'Content Calendar Review', date: '2026-07-23', time: '3:00 PM', duration: '30 min', location: 'Zoom', type: 'Creative Review', status: 'confirmed', notes: 'Walk through the August content calendar and reel concepts.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }] },
      { id: 3, title: 'Monthly Check-In', date: '2026-08-03', time: '9:00 AM', duration: '30 min', location: 'Phone', type: 'Check-In', status: 'confirmed', notes: 'Standing monthly sync on plan progress.', attendees: [{ name: 'Priya Shah', initials: 'PS', color: BLUE }] },
    ],
    notifications: [
      { id: 1, title: 'Upcoming appointment', body: 'Content Calendar Review starts in 3 days', time: 'Today, 9:15 AM', unread: true, glyph: '🕑', iconBg: ACCENT_SOFT },
      { id: 2, title: 'Message from Priya Shah', body: 'Sent over three reel concepts for next week', time: 'Jul 18', unread: true, glyph: '✉', iconBg: ACCENT_SOFT },
      { id: 3, title: 'Invoice ready', body: 'Your monthly invoice is ready to view', time: 'Jul 15', unread: false, glyph: '$', iconBg: 'rgba(15,23,42,0.06)' },
    ],
  },
];
